name: CI Pipeline

on: [push, pull_request]

jobs:
  test_node_lts:
    runs-on: ubuntu-latest

    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 3000:80
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 24.x
      uses: actions/setup-node@v1
      with:
        node-version: 24.x
    - run: npm ci
    - run: npm run tsc
    - run: npm run buildcjs
    - run: npm run coverage
    - run: npm prune --omit=dev
    - run: npm link --ignore-scripts
    - run: npm i node-fetch-cache@5.1 --prefix plugins/redis
    - run: npm link --ignore-scripts node-fetch-cache
      working-directory: plugins/redis
    - run: npm run coverage
      working-directory: plugins/redis
    - name: Upload root coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/lcov.info
        flags: root
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload redis coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./plugins/redis/coverage/lcov.info
        flags: redis
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test_node_other:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.0, 18.x, 20.x, 22.x, 26.x]

    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 3000:80
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run tsc
    - run: npm run buildcjs
    - run: npm test
    - run: npm prune --omit=dev
    - run: npm link --ignore-scripts
    - run: npm i node-fetch-cache@5.1 --prefix plugins/redis
    - run: npm link --ignore-scripts node-fetch-cache
      working-directory: plugins/redis
    - run: npm test
      working-directory: plugins/redis
